repos:
-   repo: https://github.com/ambv/black
    rev: 24.4.2
    hooks:
    - id: black
      language_version: python3.12.3
      args: [--line-length=200, --verbose]

- repo: https://github.com/Riverside-Healthcare/djLint
  rev: v1.34.1  
  hooks:
  - id: djlint
    name: djLint
    entry: djlint
    language: python
    types: [html]
    args: [--reformat]  